name: ml_demo
description: Flutter Ml Demo by Alpha team

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  speech_to_text: ^7.0.0
  avatar_glow: ^2.0.2
  url_launcher: ^6.1.9
  clipboard: ^0.1.3
  flutter_tts: ^4.0.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/app_logo.png"
  windows:
    generate: true
    image_path: "assets/app_logo.png"
  macos:
    generate: true
    image_path: "assets/app_logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
